### ISSUE TITLE
Hlds Cs.16

### ISSUE THREAD

**Issue by murderBrBr** [hyperxpro/SourceEngineQueryCacher#12]
Application works very well, but it seems that old cs1.6 clients cannot list the server in the favorites.

What does not happen with steam and some newer versions of no-steam.

Can you solve this?

**Comment by murderBrBr** [comment]
When the player opens the cs 1.6 and considering that he has registered the server in the list of favorites, the following sequence occurs.

Player request ff ff ff ff 54 53 6F 75 72 63 65 20 45 6E 67 69 6E 65 20 51 75 65 72 79 00
Server Response ff ff ff ff 6d
Server Responde ff ff ff ff 49
__________________________________

Sometimes it happens this way
Player request ff ff ff ff 54 53 6F 75 72 63 65 20 45 6E 67 69 6E 65 20 51 75 65 72 79 00
Server Response ff ff ff ff 6d
Server Responde ff ff ff ff 49
Player request ff ff ff ff 54 53 6F 75 72 63 65 20 45 6E 67 69 6E 65 20 51 75 65 72 79 00
Server Response ff ff ff ff 6d
Server Response ff ff ff ff 44
Server Responde ff ff ff ff 49
______________________________

When the player clicks on the server to see details, such as players, time, Scores...
Player request ff ff ff ff 54 53 6F 75 72 63 65 20 45 6E 67 69 6E 65 20 51 75 65 72 79 00
Server Response ff ff ff ff 6d
Server Responde ff ff ff ff 49
Player request  ff ff ff ff 55 ff ff ff ff
Server response ff ff ff ff 41
Player request ff ff ff ff 55
Server response ff ff ff ff 44

____________________________________

When the player clicks on the server to connect
Player request ff ff ff ff 54 53 6F 75 72 63 65 20 45 6E 67 69 6E 65 20 51 75 65 72 79 00
Server Response ff ff ff ff 6d
Server Responde ff ff ff ff 49
Player request ff ff ff ff 67 65 74 63  ( getc challenge  )
Server response ff ff ff ff 41
Player response ff ff ff ff 63

**Comment by hyperxpro** [comment]
I rely on this for Packet Structure information.

https://developer.valvesoftware.com/wiki/Server_queries

**Comment by murderBrBr** [comment]
> I rely on this for Packet Structure information.
> 
> https://developer.valvesoftware.com/wiki/Server_queries


I get it. But I believe that what is on the site is not equal to HLDS.

Also the version available here on github does not have all the dependencies to be compiled. I would even try to adapt it to HLDS.

example

#define A2S_INFO_REQUEST 0x54
#define A2S_RULES_REQUEST 0x56
#define A2S_PLAYERS_REQUEST 0x55

#define A2S_INFO_RESPONSE_0           0x6d
#define A2S_INFO_RESPONSE_1           0x49
#define A2S_PLAYERS_RESPONSE_0     0x41
#define A2S_PLAYERS_RESPONSE_1     0x44

real packtes "\xFF\xFF\xFF\xFF"

**Comment by murderBrBr** [comment]
I mistake there
#define A2S_RULES_RESPONSE 0x45

45 to 41

**Comment by hyperxpro** [comment]
So you mean Valve and HLDS has different packet structure?

**Comment by murderBrBr** [comment]
> So you mean Valve and HLDS has different packet structure?

Yes.
              Not entirely different, but your application is not able to respond to all players

I gave examples:
x44,  x49 , x6d
One more explanation of what I'm trying to say, x41, is never a player request.
You described in the iptables rule that you enter an x41 request, but this is the result of an x55 player request.
So what is on the site is obviously not an exclusive HLDS rule and involves other games.

Positive examples:
ff ff ff ff 54
ff f ff ff 55
These are part of the structure and the rest is a matter of review.

If you are able to test hlds and monitor the packages it will confirm what I am saying.

**Comment by hyperxpro** [comment]
Not sure from where should I start. Can you point issues in the current code so It'd be easier for me to understand and fix?

**Comment by murderBrBr** [comment]
> Not sure from where should I start. Can you point issues in the current code so It'd be easier for me to understand and fix?

I don't have java skills, sorry.

    S2A_CHALLENGE = 0x41;   ( you put )
    S2A_INFO      = 0x49;  ( you put )
    S2A_INFO_OLD  = 0x6D; ( missing this ) // Old GoldSource
    S2A_PLAYER    = 0x44; ( you put )

https://developer.valvesoftware.com/wiki/Server_queries
GoldSource servers reply using the same response as Source servers. Older and pre-Steam servers still reply with the response format below. GoldSource can be distinguished from Source via AppIDs.

Header | byte | Always equal to 'm' (0x6D)
maybe that's the problem.

So all players, including old versions will be able to list

Good Aplication

**Comment by hyperxpro** [comment]
Makes sense now. I developed this application for up-to-date server versions. I'm not sure how useful it'd be to add old queries support.

**Comment by murderBrBr** [comment]
> Makes sense now. I developed this application for up-to-date server versions. I'm not sure how useful it'd be to add old queries support.

A parallel version would be nice, partially solve servers that run with rehlds.

**Comment by murderBrBr** [comment]
Packets.java

you declared, A2S_INFO_RESPONSE_HEADER.
{-1, -1, -1, -1, 73} = FFFFFFFF49

but you never use it in code ( A2S_INFO_RESPONSE_HEADER )
A2S_INFO_RESPONSE is not complete. So people posted here that the server does not appear on the list.

you can pass your email? I want to show the video with and without application.

**Comment by hyperxpro** [comment]
I've decided not to support Goldsource. Sorry for the inconvenience. Closing the issue now.
