### ISSUE TITLE
[feature] - one process/one cfg for all servers

### ISSUE THREAD

**Issue by xSL0W** [hyperxpro/SourceEngineQueryCacher#14]
Hello! It would be great to use one process for all the servers and a single config file for all servers.
For example if I have 10 servers on a dedicated server I want to redirect all the queries to the a2s cacher without manually creating config files & starting a new process one by one for all my servers.

**Comment by hyperxpro** [comment]
Application is not designed to handle multiple servers at once because it'll make the application architecture more complex.

**Comment by xSL0W** [comment]
Will it be hard? Seems like a very good a2s protection and many people would use it.

**Comment by hyperxpro** [comment]
Yes, it's hard to implement. But I'm not sure how it'll increase a2s protection.

**Comment by xSL0W** [comment]
It will not increase the protection itself but it would be much easier to scale up more servers

**Comment by hyperxpro** [comment]
Closing this for now as I don't have plans for it. If I ever implement this, I'll tag this issue with the Pull Request. Have a good day!
