### ISSUE TITLE
Crashing and not displaying on server browser

### ISSUE THREAD

**Issue by ghost** [hyperxpro/SourceEngineQueryCacher#15]
**Issue:**
Server cannot be found on the CSGO server browser or favorites. When joining the server via console connect X.X.X.X:27017 the server seems to crash. Errors can be found below.

**OS:** Ubuntu 20.04.2 LTS (Focal Fossa)

java -version
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

**Command**
java -jar SourceEngineQueryCacher-1.6.3.jar -port 9110 -gameip <server ip> -gameport 27017 -b -p

**iptables**
```
sudo iptables -t nat -A PREROUTING -p udp --dport 27017 --match string --algo kmp --hex-string '|FFFFFFFF54|' -j REDIRECT --to-ports 9110
sudo iptables -t nat -A PREROUTING -p udp --dport 27017 --match string --algo kmp --hex-string '|FFFFFFFF55|' -j REDIRECT --to-ports 9110
sudo iptables -t nat -A PREROUTING -p udp --dport 27017 --match string --algo kmp --hex-string '|FFFFFFFF41|' -j REDIRECT --to-ports 9110
```

**Errors**

```
java -jar SourceEngineQueryCacher-1.6.3.jar -port 9110 -gameip <server IP> -gameport 27017 -b -p
19 Feb 2021 01:24:58.971 [epollEventLoopGroup-2-2] INFO  c.a.s.Main - Server Started on Address: 127.0.0.1:9110
19 Feb 2021 01:24:58.971 [Thread-1] INFO  c.a.s.u.CacheCleaner - Starting Challenge Code Cache Cleaner
19 Feb 2021 01:24:58.963 [epollEventLoopGroup-2-1] INFO  c.a.s.Main - Server Started on Address: 127.0.0.1:9110
19 Feb 2021 01:24:58.994 [Thread-0] INFO  c.a.s.Stats - Starting Stats, PPS Enabled: true, bPS Enabled: true
[01:24:59.003] [STATS] PPS: 0 | bPS: 0
[01:25:00.035] [STATS] PPS: 0 | bPS: 0

Message from syslogd@server at Feb 19 01:25:52 ...
 kernel:[  261.323295] Kernel panic - not syncing: Fatal exception in interrupt
```

Putty closes connection with "Network error: Software caused connection abort"

**Comment by hyperxpro** [comment]
It's a Kernel Panic for some reason. More info needed.

**Comment by ghost** [comment]
I'm using pterodactyl panel and I currently have it configured with host networking(https://pterodactyl.io/daemon/0.6/configuration.html#custom-network-interfaces) for the docker containers. Having it set as host causes I assume this kernel panic/issues when using SourceEngineQueryCacher. When I switch the networking back to pterodactyl_nw then everything seems to be working. 

The reason for host networking is because it solved my issue at the time of being able to use different ips for each game server.
However I think this may be the solution instead of host networking https://github.com/pterodactyl/panel/issues/459#issuecomment-373942796 and maybe it will work fine with SourceEngineQueryCacher however at this moment I have not tested this out but when I get around to it I will update this.

**Update:** The solution above works.

**Comment by hyperxpro** [comment]
I cannot say much but this issue is outside the scope of `SourceEngineQueryCacher`.

**Comment by ghost** [comment]
The solution I posted above solved my original issue but how do you configure this for multiple ips for example:
Server 1: X.X.X.17 port 27015
Server 2: X.X.X.18 port 27015

The command for server 1 would be:
`java -jar SourceEngineQueryCacher-1.6.3.jar -port 9110 -gameport 27015 -gameip X.X.X.17`

The command for server 2 would be:
`java -jar SourceEngineQueryCacher-1.6.3.jar -port 9112 -gameport 27015 -gameip X.X.X.18`

What would the iptables be in this case? Would this be correct?
```
iptables -t nat -A PREROUTING -s X.X.X.17 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF54|' -j REDIRECT --to-ports 9110
iptables -t nat -A PREROUTING -s X.X.X.17 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF55|' -j REDIRECT --to-ports 9110
iptables -t nat -A PREROUTING -s X.X.X.17 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF41|' -j REDIRECT --to-ports 9110
```

**Comment by hyperxpro** [comment]
These are the correct ones:

```
iptables -t nat -A PREROUTING -d X.X.X.17 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF54|' -j REDIRECT --to-ports 9110
iptables -t nat -A PREROUTING -d X.X.X.17 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF55|' -j REDIRECT --to-ports 9110
iptables -t nat -A PREROUTING -d X.X.X.17 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF41|' -j REDIRECT --to-ports 9110
```
```
iptables -t nat -A PREROUTING -d X.X.X.18 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF54|' -j REDIRECT --to-ports 9112
iptables -t nat -A PREROUTING -d X.X.X.18 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF55|' -j REDIRECT --to-ports 9112
iptables -t nat -A PREROUTING -d X.X.X.18 -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF41|' -j REDIRECT --to-ports 9112
```
