### ISSUE TITLE
SEQC 1.6.5 Bugs (Favorite and Online)

### ISSUE THREAD

**Issue by hks27d** [hyperxpro/SourceEngineQueryCacher#17]
Hello! We managed to use 1.6.3 version for months. Everything ran very good and SourceEngineQueryCacher patched the attacks from our servers. But for now, we updated to 1.6.5 version and everything seemed to be working fine.

After a few days, I've noticed that the only issue is that the server is not always displaying online on favorite servers in CSGO. We have to do a REFRESH more frequently in order to show the server online. The same issue is in online environment. The server is not always detected as being online.

Specs:
Debian 10 (Updated and Upgraded for the last versions of dependencies)
LinuxGSM CSGO servers with autoupdate (cronjob)
16GB RAM

Example of our commands:
sudo iptables -t nat -A PREROUTING -d SERVERIPADDRESS -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF54|' -j REDIRECT --to-ports 9110
sudo iptables -t nat -A PREROUTING -d SERVERIPADDRESS -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF55|' -j REDIRECT --to-ports 9110
sudo iptables -t nat -A PREROUTING -d SERVERIPADDRESS -p udp --dport 27015 --match string --algo kmp --hex-string '|FFFFFFFF41|' -j REDIRECT --to-ports 9110

In screen: java -jar /root/SourceEngineQueryCacher-1.6.5.jar -c /root/SourceEngineQueryCacher-1.6.5/cacher194.conf

Our cacher194.conf:
Threads=2
StatsPPS=true
StatsbPS=true
GameUpdateInterval=10000
GameUpdateSocketTimeout=1000
MaxChallengeCode=100000
ChallengeCacheCleanerInterval=1000
ChallengeCodeTTL=5000
ChallengeCodeCacheConcurrency=8
LocalServerIPAddress=0.0.0.0
LocalServerPort=9110
GameServerIPAddress=SERVERIPADDRESS
GameServerPort=27015
ReceiveBufferSize=65535
SendBufferSize=65535
FixedReceiveAllocatorBufferSize=65535

As you can see in the photo below, our Cacher is working correctly.
![Untitled](https://user-images.githubusercontent.com/51793958/124110468-ee0db480-da70-11eb-8584-50da38d31a48.png)

But in SourceBans the server displays sometimes as being offline:
![sb](https://user-images.githubusercontent.com/51793958/124111500-06320380-da72-11eb-8c8b-3d1803f8e27a.png)

I have to mention the fact that after many refreshes of the webpage - SourceBans displays our server as being online:
![sb-working](https://user-images.githubusercontent.com/51793958/124111558-1944d380-da72-11eb-9eb3-7242c2d41e42.png)

In SourceEngineQueryCacher 1.6.3 this issue (server offline/online) was not present.
Do you have any ideea why it's happening? Is it a BUG?

**Comment by hyperxpro** [comment]
I will try to roll an update fixing this.

**Comment by hyperxpro** [comment]
I tested this and it's running correctly. Did you try increasing `ReceiveBufferSize` and `SendBufferSize`?

**Comment by hyperxpro** [comment]
Also, which kernel you're using?

**Comment by hks27d** [comment]
**Kernel: 4.19.0-14-amd64**

The settings for BufferSize are **default**:
_ReceiveBufferSize=65535
SendBufferSize=65535
FixedReceiveAllocatorBufferSize=65535_

**Comment by hks27d** [comment]
The only setting modified by us is this:
_GameUpdateInterval=10000_

We increased it from the default value (1000) to 10000. Just that.

**Comment by hks27d** [comment]
> I tested this and it's running correctly. Did you try increasing `ReceiveBufferSize` and `SendBufferSize`?

I've just tested now:
ReceiveBufferSize=655350
SendBufferSize=655350
FixedReceiveAllocatorBufferSize=655350

The same issue is happening. The server disappears completely from favorites because of the cacher itself.
The server is showed as OFFLINE most of the time on SourceBans website and on favorites (in CSGO).
The issue seems to be more prominent now. 

Do you recommend other values for **ReceiveBufferSize**, **SendBufferSize** and **FixedReceiveAllocatorBufferSize**?
On SourceEngineQueryCacher 1.6.3 we encountered this kind of situations very rarely. Almost never.

**Comment by hks27d** [comment]
As I can see from your Git Releases, SEQC v1.6.5 uses AdaptiveReceiveBuffer.

I'll test SEQC v1.6.4 Release because it doesn't have AdaptiveReceiveBuffer. It may be better. I will be back with the results.

**Comment by hks27d** [comment]
### I'm here with the results:
AdaptiveReceiveBuffer from Source Engine Query Cacher v1.6.5 is buggy.
The BUG reported here is solved by using SEQC v1.6.4 instead of SEQC v1.6.5.
You can close this issue now.

### Conclusions:
We will use SEQC v1.6.4 from now on.

### A final message for the developer:
We really appreciate your work.
Thank you!

**Comment by hyperxpro** [comment]
Thanks a lot for investigating the issue. Would you like to participate in the Beta release?

**Comment by hks27d** [comment]
@hyperxpro 
Hi! Yes, I'll participate in the Beta release.
In 2 weeks I will be free and ready to participate. Is it too late?

**Comment by hks27d** [comment]
@hyperxpro  Hi! Yes, I'll participate in the Beta release.
In 2 weeks I will be free and ready to give you feedback.

**Comment by hyperxpro** [comment]
v1.6.6 is released. PTAL.

**Comment by hks27d** [comment]
Hello! @hyperxpro 
Is v1.6.6 using AdaptiveReceiveBuffer or not?

Thank you!

**Comment by hyperxpro** [comment]
It uses `AdaptiveReceiveBuffer`.

**Comment by hks27d** [comment]
@hyperxpro  Thank you for your answer.
I've also noticed the changelog:

> Use HashMap instead of Cache
> Remove unnecessary dependencies.
> Upgrade Netty to 4.1.66.Final.
> Use voidPromise() to accelerate performance.
> Remove MaxChallengeCode, ChallengeCacheCleanerInterval, and ChallengeCodeCacheConcurrency.

I have some quick questions.
1. Was AdaptiveReceiveBuffer fixed on v1.6.6 compared to v1.6.5? I can't figure this out from the changelog.
2. Is there any possibility for you to do a new version of the software without AdaptiveReceiveBuffer? I may want to test both of them to identify issues and to see which one is better.

Thank you!

**Comment by hyperxpro** [comment]
`AdaptiveRecvByteBufAllocator` is fine. It's just efficient compared to `FixedRecvByteBufAllocator` because it can resize itself depending upon the payload.

```java
    static final int DEFAULT_MINIMUM = 64;
    // Use an initial value that is bigger than the common MTU of 1500
    static final int DEFAULT_INITIAL = 2048;
    static final int DEFAULT_MAXIMUM = 65536;
```

The problem might exist in UDP_GRO. The earlier versions don't have that enabled. However, 1.6.X has enabled.

**Comment by xSL0W** [comment]
Hi, im facing the same issue on version 1.6.6 too
How can I help?

**Comment by hyperxpro** [comment]
@xSL0W I will add an option to disable UDP GRO in the next release. Hopefully, that will solve the issue.

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
