### ISSUE TITLE
SEQC: Maintain the same Latency for the server

### ISSUE THREAD

**Issue by hks27d** [hyperxpro/SourceEngineQueryCacher#18]
### Introduction
Hello! We're using SourceEngineQueryCacher 1.6.4 for CSGO game servers.
The Cacher runs ok, it patches the attacks and everything's ok.

### We did some tests
We've just tested the latency on the same network interface for many individual players to see the results.

### What did we discover?
Cacher brings improvements for latency too.
Without Cacher our game server (CSGO) has a stable latency (about 20ms).
With Cacher our game server (CSGO) has a stable latency (about 8ms) and sometimes the number goes higher (about 15-18ms).

### The issue:
The problem is that the latency is never stable at 8ms. Sometimes it goes higher at 15-18ms.
Why does it happen and how can we permanently fix it? We want it stable at the lower value (8ms).
We want to use Cacher to maintain a reduced latency for our game servers (CSGO) all the time, without any burst interruptions.

### Screenshot (without Cacher):
![20](https://user-images.githubusercontent.com/51793958/124193690-f6e1a300-dacf-11eb-960e-8949d9e245aa.png)

### Screenshot (with Cacher):
![8](https://user-images.githubusercontent.com/51793958/124193700-fcd78400-dacf-11eb-92f6-cc9036556cc2.png)

### Screenshot (with Cacher - latency patch interruptions):
![intera](https://user-images.githubusercontent.com/51793958/124194520-686e2100-dad1-11eb-829f-bb0dff9b4e81.png)

**Comment by hks27d** [comment]
We mention the fact that other friends with dedicated servers have stable low latency all the time for their game servers by using Cacher. They don't have burst interruptions like us. We don't know why.
Maybe they have other kernel version.

**Comment by hyperxpro** [comment]
I will investigate and get back to you.

**Comment by hks27d** [comment]
Ok @hyperxpro . We are looking forward for a solution from you.
We use Debian 10 (all dependencies updated and upgraded).
Kernel version: 4.19.0-14-amd64

Thank you!

**Comment by xSL0W** [comment]
Same issue for me. Debian 10 user too
Tried different kernel versions, still the same.

**Comment by hyperxpro** [comment]
Does it happen during full load or just randomly?

**Comment by xSL0W** [comment]
Depends on what you mean by full load. I have like 10 query requests per second, its nearly idle i guess.
Its random or I guess it depends on variable `GameUpdateInterval`
Are the queries updated immediately after x seconds or it depends on client request to be updated?

**Comment by hyperxpro** [comment]
> Are the queries updated immediately after x seconds or it depends on client request to be updated?

It's updated automatically via a separate thread. I also tested it right now with 1 Gbps traffic. Only 3% of packets faced latency issues. Maybe it happened due to the Garbage Collector, can't say.

Maybe it'll be fixed in future releases after Java 17 LTS is released via Shenandoah GC.

**Comment by Michael-Phoenix** [comment]
could you guys check if your problem still appears with this version:
https://github.com/Michael-Phoenix/SourceEngineQueryCacher/releases/tag/1.7.1
I'm running it on a full 100 player server for a day already and our problems of the server being hard to find /not showing up in server browser has been fixed

**Comment by xSL0W** [comment]
> could you guys check if your problem still appears with this version: https://github.com/Michael-Phoenix/SourceEngineQueryCacher/releases/tag/1.7.1 I'm running it on a full 100 player server for a day already and our problems of the server being hard to find /not showing up in server browser has been fixed

https://hatebin.com/igqoqcwjfa

hi, my packets are being dropped

**Comment by Michael-Phoenix** [comment]
> > could you guys check if your problem still appears with this version: https://github.com/Michael-Phoenix/SourceEngineQueryCacher/releases/tag/1.7.1 I'm running it on a full 100 player server for a day already and our problems of the server being hard to find /not showing up in server browser has been fixed
> 
> https://hatebin.com/igqoqcwjfa
> 
> hi, my packets are being dropped

Seems to me like it is not configured correctly. Please provide the command line you use to run it as well as the config file(if you use one) as well as the server IP and query port you use.

**Comment by xSL0W** [comment]
> > > could you guys check if your problem still appears with this version: https://github.com/Michael-Phoenix/SourceEngineQueryCacher/releases/tag/1.7.1 I'm running it on a full 100 player server for a day already and our problems of the server being hard to find /not showing up in server browser has been fixed
> > 
> > 
> > https://hatebin.com/igqoqcwjfa
> > hi, my packets are being dropped
> 
> Seems to me like it is not configured correctly. Please provide the command line you use to run it as well as the config file(if you use one) as well as the server IP and query port you use.

Hi, here's everything

Command line: 
/usr/bin/java -jar /root/a2s/SourceEngineQueryCacher-1.7.1.jar -c /root/a2s/go.test.conf

Settings:

Threads=1
StatsPPS=true
StatsbPS=true
GameUpdateRate=1000
GameUpdateTimeout=1000
ChallengeCodeTTL=5000
LocalServerIPAddress=0.0.0.0
LocalServerPort=9111
GameServerIPAddress=185.244.148.132
GameServerPort=27015
ReceiveBufferSize=65535
SendBufferSize=65535

Gameserver ip & port: 185.244.148.132:27015

Also java version:
root@server0:~/a2s# java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

Os: debian10

**Comment by Michael-Phoenix** [comment]
Could you do me a favour and set LocalServerIPAddress=127.0.0.1

**Comment by xSL0W** [comment]
> Could you do me a favour and set LocalServerIPAddress=127.0.0.1

I tried that too, no errors, but no traffic

with 0.0.0.0 i get traffic but errors too

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
