### ISSUE TITLE
ff ff ff ff 56 query and response

### ISSUE THREAD

**Issue by ThePureCC** [hyperxpro/SourceEngineQueryCacher#19]
I host a Rust game server. The game Rust, not the programming language. 

The game uses ffffffff56(A2S_RULES) for requesting server description info with a ffffffff55 challenge to begin with. 

Currently, when running the cacher, server info does not get displayed when client requests this information.

Packet exchange happens in the following sequence(on a normal server without cacher):

1. local -> remote: ff ff ff ff 55 ff ff ff ff (requesting for challenge)
2. remote -> local: ff ff ff ff 41 7f 14 bb 00
3. local -> remote:  ff ff ff ff 56 7f 14 bb 00
4. remote -> local: ff ff ff ff 45 23 00 ..... (with server description in plain text)

Right now, the server does 1,2,3, but when local sends ff ff ff ff 56, server doesn't respond to it.

Could you please consider supporting ff ff ff ff 56 as well?

**Comment by ThePureCC** [comment]
@hyperxpro Thanks for the self assigning. I'm wondering if you have an ETA for the feature?

**Comment by hyperxpro** [comment]
Expect release in first half of October 2021.

**Comment by ThePureCC** [comment]
> Expect release in first half of October 2021.

Thanks. Really appreciate it. Please let me know when it does.

**Comment by hyperxpro** [comment]
~Can you drop me an email because I need your help in implementing this?~

**Comment by Michael-Phoenix** [comment]
Challenge Request code 0x55 is for A2S_PLAYER request So if rust starts the query with that, it's kinda in a grey area, protocol wise.

@pureche
The PR https://github.com/hyperxpro/SourceEngineQueryCacher/pull/21 includes the 0x56 Packet Challenge & Response and would not have a problem with this behavior from rust, as it caches the challenge code between packet types anyway <3

(Most servers only ask for a single challenge code with their first packet and supply it to all the following Packets for a given time. As opposed to one challenge code per A2S_INFO/_PLAYERS/_RULES Packet)

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
