### ISSUE TITLE
Team Fortress 2 broken since A2S_INFO update

### ISSUE THREAD

**Issue by Hagvan** [hyperxpro/SourceEngineQueryCacher#20]
Alright so, I was using similar software to cache source queries around 2 years ago when hosting events in order to mitigate flood attacks.
Recently I tried using the Mono version and this version of query caching and it is not working anymore because Valve enabled A2S_INFO to require challenge. It makes the packet length reach up to 29 (former A2S_INFO + 4 bytes challenge).

https://steamcommunity.com/discussions/forum/14/2974028351344359625/

Also, I did some Wireshark investigation myself:

>ffffffff54536f7572636520456e67696e6520517565727900

<ffffffff4129f9d53c (challenge = 29f9d53c)

>ffffffff54536f7572636520456e67696e652051756572790029f9d53c

<ffffffff49114c696e757847534d006b6f74685f686172766573745f6576656e74007466005465616d20466f72747265737300b801002000646c00013638333038393900b1876907f8d10be648400163702c696e637265617365645f6d6178706c617965727300b801000000000000

There are also A2S_PLAYER afterward but I believe they should still be working if A2S_INFO is fixed.

I am going to make a fork and try to implement the challenge myself, but help is welcome. I think it should be rather simple just need to figure the rest of your code, which is not all that much. :)

**Comment by Hagvan** [comment]
Okay, I reused a lot of the code for A2S_PLAYER to add the challenge processing to A2S_INFO.
I guess since there are games which maybe don't use challenge yet, should there be a config option to toggle the challenge processing code?

**Comment by hyperxpro** [comment]
You can add a new option to enable A2S_INFO with Challenge. Users can toggle this through config file or process arguments.

And thanks for your efforts towards this new feature.

**Comment by Hagvan** [comment]
Probably going to make it next week. Won't be home until next weekend.

**Comment by trollollol123** [comment]
Was the A2S_INFO ever fixed? :)

**Comment by Hagvan** [comment]
Yes, I did fix it. I actually completely forgot about it. I still need to add a config option to enable the challenge and also in some games it doesn't seem to work, probably some other query is used which is not supported.

**Comment by TuXEKRO** [comment]
Can someone confirm that it works for Garrys Mod? I'm trying to get it to work but I get the following error and I don't know if it's because of this:
`dUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 256), A2S_PLAYER: PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 256), A2S_RULES: PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 256)`

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
