### ISSUE TITLE
при атаке получаю много спама

### ISSUE THREAD

**Issue by cshost1** [hyperxpro/SourceEngineQueryCacher#30]
10 Mar 2022 14:17:09.858 [epollEventLoopGroup-2-1] ERROR c.a.s.Handler - Caught Error
io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Invalid argument
10 Mar 2022 14:17:10.853 [epollEventLoopGroup-2-4] ERROR c.a.s.Handler - Dropping query request because Cache is not ready. A2S_INFO: PooledUnsafeDirectByteBuf(ridx: 0, widx: 87, cap: 256), A2S_PLAYER: PooledUnsafeDirectByteBuf(ridx: 0, widx: 21, cap: 256)

**Comment by hyperxpro** [comment]
Please use English.

**Comment by cshost1** [comment]
ok, i try
if active ddos tsource i have this spam in console

**Comment by cshost1** [comment]
problem 2:
if active proxy and kill game server process, proxy stay work and show me server still works

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
