### ISSUE TITLE
errors v171

### ISSUE THREAD

**Issue by cshost1** [hyperxpro/SourceEngineQueryCacher#31]
![2022-03-12_122652](https://user-images.githubusercontent.com/100172301/158014392-928ed00e-c97a-41c8-9c98-09dc7a2c86ea.jpg)
version 1.7.1

**Comment by hyperxpro** [comment]
Which game?

**Comment by cshost1** [comment]
> Which game?

cs 1.6

**Comment by hyperxpro** [comment]
How did you got 1.7.1 release? I've never released it.

**Comment by cshost1** [comment]
> How did you got 1.7.1 release? I've never released it.

https://github.com/Michael-Phoenix/SourceEngineQueryCacher/tree/1.7.1 this url issue redirect to this page

**Comment by cshost1** [comment]
![2022-03-12_123506](https://user-images.githubusercontent.com/100172301/158014636-a7d3318c-3d4b-4d32-b6cb-1abb5f38f9a8.jpg)
vers 1.6.6 if ddos tsource 
if not ddos, all ok

**Comment by hyperxpro** [comment]
> > How did you got 1.7.1 release? I've never released it.
> 
> https://github.com/Michael-Phoenix/SourceEngineQueryCacher/tree/1.7.1 this url issue redirect to this page

It's a fork so I don't provide direct support for it.

**Comment by hyperxpro** [comment]
> ![2022-03-12_123506](https://user-images.githubusercontent.com/100172301/158014636-a7d3318c-3d4b-4d32-b6cb-1abb5f38f9a8.jpg) vers 1.6.6 if ddos tsource if not ddos, all ok

Are you using IPv6?

**Comment by cshost1** [comment]
> > ![2022-03-12_123506](https://user-images.githubusercontent.com/100172301/158014636-a7d3318c-3d4b-4d32-b6cb-1abb5f38f9a8.jpg) vers 1.6.6 if ddos tsource if not ddos, all ok
> 
> Are you using IPv6?

v4

**Comment by hyperxpro** [comment]
Will investigate.

**Comment by cshost1** [comment]
![2022-03-12_124044](https://user-images.githubusercontent.com/100172301/158014868-c8fd8c00-a4b5-44ab-88db-2a8eea532f5c.jpg)
if ddos disable - script work ok

**Comment by Biceeeeepss** [comment]
Hey,

That version that is forked (1.7.1) is bugged, I know because I tried it too. :/

Can you try this version?
https://github.com/Biceeeeepss/SourceEngineQueryCacher/releases/tag/v2.0

Also set more threads in config, ex. 16 or more.

**Comment by cshost1** [comment]
> Hey,
> 
> That version that is forked (1.7.1) is bugged, I know because I tried it too. :/
> 
> Can you try this version? https://github.com/Biceeeeepss/SourceEngineQueryCacher/releases/tag/v2.0
> 
> Also set more threads in config, ex. 16 or more.

![2022-03-12_143741](https://user-images.githubusercontent.com/100172301/158018241-6a7d3b11-4315-4070-b814-e9ed0860dd7f.jpg)
possibly clogged conntrack?

**Comment by cshost1** [comment]
![2022-03-12_150956](https://user-images.githubusercontent.com/100172301/158019220-a6a9399a-dad1-4001-8c64-8a60635e2fe1.jpg)
watch this. i think it conntrack is full

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
