### ISSUE TITLE
SourceEngineQueryCacher v2-wip is broken - it doesn't start

### ISSUE THREAD

**Issue by hks27d** [hyperxpro/SourceEngineQueryCacher#32]
### Introduction
Hello! The issue is about this version of cacher: https://github.com/hyperxpro/SourceEngineQueryCacher/tree/v2-wip

### What's the main issue
Version 2 of the cacher seems to be broken. It won't load after a successful compilation with mvn.
It won't loat either by itself or using the config file.

In the file pom.xml it's also written:
```
<java.version>17</java.version>
<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
```

### But in Github page of the SECQ it's written this:

```
How to run:
Download and Install Java 11.
```

For which Java version is this actually written?
Anyway, let's skip this misspelling and the lack of proper instructions.

### What I've tried:

1. Compiling with Java 11 - Fail compilation process
2. Compiling with Java 17 - Fail compilation process
3. Compiling with Java 11, but modifying the required java version in pom.xml - Succeeded building the jar file with mvn clean package
4. Compiling with Java 17, but modifying the required java version in pom.xml - Fail compilation process

### What's actually happening:
SECQ won't start.

- I had Java 11 before - same issues
- Now I have Java 17 - same issues

```
java version "17.X.X"
Java(TM) SE Runtime Environment (build 17 LTS)
Java HotSpot(TM) 64-Bit Server VM (17+12-LTS, mixed mode, sharing)
```

I've removed the versions of the software installed from the rows above.
It's enough to see that it's Java 17 there, fully working.
Photo with update alternatives --config-java: https://i.postimg.cc/Hk8WPCcH/java-v.png

Please have in mind that the file exists in the path, I've also tried with chmod +x for the jar files.
SourceEngineQueryCacher v2 won't work either way.

### OS & Specs of the testing machine:
- Debian 10 Buster
- Kernel info: 5.17
- CPU: Intel
- RAM: 32GB
- Full control: no VPS, no linux virtualization (no docker or anything else)

### Photos with SECQ depending on the directory I'm in:
https://i.postimg.cc/vZhhjCpq/cacher-s.png
https://i.postimg.cc/cJ5m1w1f/new-err.png

We are looking forward for a reply from you.
Thank you! @hyperxpro

**Comment by hyperxpro** [comment]
~Hey There!~

~Thanks for filing a detailed bug report.~

~The reason why you're not able to compile and run v2 is that v2 is still in development. However, due to the memory leak issue in Netty 5, I have to halt the development temporarily until the memory leak issue is fixed in Netty 5.~

~This should not take too long. I'm expecting to release the beta version of v2 by end of June 2022. If you're interested in a beta trial then drop me a message on Discord `HyperX_Pro#4804`.~

~Have a good day!~

~Regards~
~Aayush Atharva~

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
