### ISSUE TITLE
Any idea for Qconnect attack?

### ISSUE THREAD

**Issue by wackod** [hyperxpro/SourceEngineQueryCacher#35]
the packet that player connect server can use for ddos too  like A2S INFO

**Comment by hyperxpro** [comment]
Can you provide more details?

**Comment by wackod** [comment]
https://steamcommunity.com/discussions/forum/14/2989789048633291344/

**Comment by hyperxpro** [comment]
This will be fixed in next major release.

**Comment by hyperxpro** [comment]
SourceEngineQueryCacher has reached the end of its life.
