### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by pkmnmstr98** [hyperxpro/SourceEngineQueryCacher#36]
Gmod Server does not show up on Browser. I have tried the master branch and the v2-WIP. It works only when A2SInfo is not enabled. It also throws no errors so I'm not sure whats going on. Also, im running the 64bit version of the gmod server on Ubuntu 22.

**Comment by pkmnmstr98** [comment]
Also, im running the 64bit version of the gmod server.

**Comment by hyperxpro** [comment]
Gold is not supported.
