### ISSUE TITLE
A2S_SERVERQUERY_GETCHALLENGE

### ISSUE THREAD

**Issue by wackod** [hyperxpro/SourceEngineQueryCacher#5]
in some game  this request still work  and can use for attack

**Comment by hyperxpro** [comment]
Can you explain how the A2S_SERVERQUERY_CHALLENGE packet can be used for attack? Reference to any documentation or something equivalent would be appreciated too.

**Comment by wackod** [comment]
example  send some A2S_SERVERQUERY_GETCHALLENGE  to Garry's Mod Server
these is some of the server give back
FF FF FF FF 41 97 D5 ED 6B
FF FF FF FF 41 A5 47 C3 08
FF FF FF FF 41 1A 83 5E DB

so  server will generate some data after FF FF FF FF 41

**Comment by wackod** [comment]
if you send a lot of A2S_SERVERQUERY_GETCHALLENGE (FF FF FF FF 57)   can slow down server too
same    you can also send a lot of fake Qconnect  to attack server 
A2S_CONNECT(FF FF FF FF 71)

**Comment by hyperxpro** [comment]
You can configure Cacher to send 1 `FF FF FF FF 41` Packet per second to game server. Then cacher will cache the response and keep serving millions of requests within a hiccup.

Cacher is capable of handling 1M+ RPS and your game server will run smoothly because it'll only reply 1 RPS.

`A2S_CONNECT` is not supported as of now but I'll add it into my backlog now.

**Comment by wackod** [comment]
by the way   how many threads i need to set in -w   to handle 50K - 1M RPS attack？

**Comment by hyperxpro** [comment]
Use this config if you wanna handle 1M+ RPS:
```
Transport=epoll
Threads=64
StatsPPS=true
StatsbPS=true
GameUpdateInterval=1000
GameUpdateSocketTimeout=1000
MaxChallengeCode=5000000
ChallengeCacheCleanerInterval=1000
ChallengeCodeTTL=5000
ChallengeCodeCacheConcurrency=128
LocalServerIPAddress=127.0.0.1
LocalServerPort=27016
GameServerIPAddress=127.0.0.1
GameServerPort=27015
ReceiveBufferSize=65535
SendBufferSize=65535
FixedReceiveAllocatorBufferSize=65535
```

**Comment by hyperxpro** [comment]
Reopen if you still have issues.
