### ISSUE TITLE
FFFFFFFF71

### ISSUE THREAD

**Issue by Lerrdy** [hyperxpro/SourceEngineQueryCacher#8]
Hey! The cacher works great for the ffffffff41, 54 and 55 queries. But we started getting attacked by ffffffff71 queries now. Game is CS:GO.

**Comment by hyperxpro** [comment]
Sorry for the super-late reply. I will take a look once I'm done with my current project.

**Comment by hyperxpro** [comment]
`ffffffff71` will not be supported because SourceEngineQueryCacher is aimed to support only query packets.
